package com.onnisoft.wahoo.model.document.enums;

public enum LanguageEnum {
	AFRIKAANS, ALBANIAN, AMHARIC, ARABIC, ARMENIAN, BASQUE, BENGALI, BYELORUSSIAN, BURMESE, BULGARIAN, CATALAN, CZECH, CHINESE, CROATIAN, DANISH, DARI, DZONGKHA, DUTCH, ENGLISH, ESPERANTO, ESTONIAN, FAROESE, FARSI, FINNISH, FRENCH, GAELIC, GALICIAN, GERMAN, GREEK, HEBREW, HINDI, HUNGARIAN, ICELANDIC, INDONESIAN, INUKTITUT_ESKIMO, ITALIAN, JAPANESE, KHMER, KOREAN, KURDISH, LAOTIAN, LATVIAN, LAPPISH, LITHUANIAN, MACEDONIAN, MALAY, MALTESE, NEPALI, NORWEGIAN, PASHTO, POLISH, PORTUGUESE, ROMANIAN, RUSSIAN, SCOTS, SERBIAN, SLOVAK, SLOVENIAN, SOMALI, SPANISH, SWEDISH, SWAHILI, TAGALOG_FILIPINO, TAJIK, TAMIL, THAI, TIBETAN, TIGRINYA, TONGAN, TURKISH, TURKMEN, UCRAINIAN, URDU, UZBEK, VIETNAMESE, WELSH;
}
