logging:
  level: WARN

  loggers:
    "subscriberApiLog": WARN
    "com.onnisoft.wahoo.api.App": WARN

  appenders:
    - type: file
      currentLogFilename: ../.logs/api-errors.log
      threshold: WARN
      logFormat: "%d{yyyy-MM-dd hh:mm:ss,SSS} []%-5p %c - %m%n"
      archive: true
      archivedLogFilenamePattern: ../.logs/api-errors-archive.%d.log.gz
      archivedFileCount: 10
    - type: console

server:
  applicationConnectors:
    - type: http
      port: 8093

  adminConnectors:
    - type: http
      port: 8083

